#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "technitium-dns"
name = "Technitium DNS"
description.en = "DNS server for privacy and security"
description.fr = "Serveur DNS pour la confidentialité et la sécurité"

version = "15.2.0~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "GPL-3.0-only"
website = "https://technitium.com/dns/"
admindoc = "https://technitium.com/dns/help.html"
userdoc = "https://technitium.com/dns/help.html"
code = "https://github.com/TechnitiumSoftware/DnsServer"
cpe = "cpe:2.3:a:technitium:dnsserver"
fund = "https://patreon.com/technitium"

[integration]
yunohost = ">= 12.1.38"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://github.com/TechnitiumSoftware/DnsServer/archive/refs/tags/v15.2.0.tar.gz"
    sha256 = "9247b3c70a8f58d336741819b4550b29937815dc535d1cc0f36ffd7cedb8860c"
    in_subdir = false
    # Careful, this autoupdate does not put the right asset, it only serves as a notification!
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "tarball"
    autoupdate.needs_manual_tweaks = true

    [resources.sources.dotnet]
    amd64.url = "https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.7/dotnet-runtime-10.0.7-linux-x64.tar.gz"
    amd64.sha256 = "825c0e34e405314c225713990601908435cb9b10cd2292fc1174eb0cde513f87"
    arm64.url = "https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.7/dotnet-runtime-10.0.7-linux-arm64.tar.gz"
    arm64.sha256 = "df43a2fdbb23b8692242e1838bcc2419faaeab613db950c7f1bf33f3b03cce1c"
    armhf.url = "https://builds.dotnet.microsoft.com/dotnet/Runtime/10.0.7/dotnet-runtime-10.0.7-linux-arm.tar.gz"
    armhf.sha256 = "022197ba766f61ca403db1210b56d47986f6d51a205afb2db34f027a27cd99c0"
    in_subdir = false

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5380
