#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "technitium-dns"
name = "Technitium DNS"
description.en = "DNS server for privacy and security"
description.fr = "Serveur DNS pour la confidentialité et la sécurité"

version = "14.3.0~ynh1"

maintainers = ["Navan Chauhan"]

[upstream]
license = "GPL-3.0-only"
website = "https://technitium.com/dns/"
admindoc = "https://technitium.com/dns/help.html"
userdoc = "https://technitium.com/dns/help.html"
code = "https://github.com/TechnitiumSoftware/DnsServer"
cpe = "cpe:2.3:a:technitium:dnsserver"
fund = "https://patreon.com/technitium"

[integration]
yunohost = ">= 12.1.18"
helpers_version = "2.1"
architectures = ["amd64", "arm64", "armhf"]
multi_instance = false

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

[resources]
    [resources.sources.main]
    url = "https://download.technitium.com/dns/archive/14.3.0/DnsServerPortable.tar.gz"
    sha256 = "9b2deaa54378e5abef1917907876ef2d0c89e0b6d09fc494e6a799b6316adea7"
    in_subdir = false
    # Careful, this autoupdate does not put the right asset, it only serves as a notification!
    autoupdate.strategy = "latest_github_tag"
    autoupdate.asset = "tarball"
    autoupdate.needs_manual_tweaks = true

    [resources.sources.dotnet]
    amd64.url = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-x64.tar.gz"
    amd64.sha256 = "9c72253df8cbdbc775c76d6dcefc057aabb0bf7c978e5c3f24ab0afed839fd1f"
    arm64.url = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm64.tar.gz"
    arm64.sha256 = "d039cbb3ef822aad0226857c1d89763c9c2a4bf339015bb11c99a7f6e62d3062"
    armhf.url = "https://builds.dotnet.microsoft.com/dotnet/aspnetcore/Runtime/9.0.11/aspnetcore-runtime-9.0.11-linux-arm.tar.gz"
    armhf.sha256 = "6ef6521e262d05302f3e52026d59b8464ae881fc983671c20e3a9e4034d7a99c"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.data_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 5380
